
import __ASTRO_IMAGE_IMPORT_Z2bUvHi from "./paintings/being here.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fbeing-here.mdx";
import __ASTRO_IMAGE_IMPORT_ZJ12U6 from "./paintings/birthing (seed).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fbirthing-seed.mdx";
import __ASTRO_IMAGE_IMPORT_ZSyT5s from "./paintings/dying (glint).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fdying-glint.mdx";
import __ASTRO_IMAGE_IMPORT_xaJVC from "./paintings/flower meditation (quartz).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fflower-meditation-quartz.mdx";
import __ASTRO_IMAGE_IMPORT_Z8HOuK from "./paintings/magic clover.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fmagic-clover.mdx";
import __ASTRO_IMAGE_IMPORT_jnC14 from "./paintings/my wish for you (safe here).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fmy-wish-for-you.mdx";
import __ASTRO_IMAGE_IMPORT_Z2fGBFl from "./paintings/reflecting (eclipse).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Freflecting-eclipse.mdx";
import __ASTRO_IMAGE_IMPORT_Z1IELjD from "./paintings/fluidly (in the water).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Ffluidly-in-the-water.mdx";
import __ASTRO_IMAGE_IMPORT_ZRfwnn from "./paintings/rebirth.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Frebirth.mdx";
import __ASTRO_IMAGE_IMPORT_ZGcHV4 from "./paintings/submerged.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fsubmerged.mdx";
import __ASTRO_IMAGE_IMPORT_1FLRyc from "./drawings/suspended, 2020.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fsuspended.mdx";
import __ASTRO_IMAGE_IMPORT_2cst7r from "./drawings/suspended, 2020.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Ftemplate-art.mdx";
import __ASTRO_IMAGE_IMPORT_Z1AoUiI from "./drawings/the day the sky opened, 2021.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fthe-day-the-sky-opened.mdx";
import __ASTRO_IMAGE_IMPORT_Bsj26 from "./paintings/void (sealed).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fvoid-sealed.mdx";
import __ASTRO_IMAGE_IMPORT_ZrAeNr from "./paintings/rebirth.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Frebirth-glint.mdx";
export default new Map([["./paintings/being here.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fbeing-here.mdx", __ASTRO_IMAGE_IMPORT_Z2bUvHi], ["./paintings/birthing (seed).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fbirthing-seed.mdx", __ASTRO_IMAGE_IMPORT_ZJ12U6], ["./paintings/dying (glint).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fdying-glint.mdx", __ASTRO_IMAGE_IMPORT_ZSyT5s], ["./paintings/flower meditation (quartz).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fflower-meditation-quartz.mdx", __ASTRO_IMAGE_IMPORT_xaJVC], ["./paintings/magic clover.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fmagic-clover.mdx", __ASTRO_IMAGE_IMPORT_Z8HOuK], ["./paintings/my wish for you (safe here).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fmy-wish-for-you.mdx", __ASTRO_IMAGE_IMPORT_jnC14], ["./paintings/reflecting (eclipse).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Freflecting-eclipse.mdx", __ASTRO_IMAGE_IMPORT_Z2fGBFl], ["./paintings/fluidly (in the water).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Ffluidly-in-the-water.mdx", __ASTRO_IMAGE_IMPORT_Z1IELjD], ["./paintings/rebirth.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Frebirth.mdx", __ASTRO_IMAGE_IMPORT_ZRfwnn], ["./paintings/submerged.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fsubmerged.mdx", __ASTRO_IMAGE_IMPORT_ZGcHV4], ["./drawings/suspended, 2020.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fsuspended.mdx", __ASTRO_IMAGE_IMPORT_1FLRyc], ["./drawings/suspended, 2020.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Ftemplate-art.mdx", __ASTRO_IMAGE_IMPORT_2cst7r], ["./drawings/the day the sky opened, 2021.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fthe-day-the-sky-opened.mdx", __ASTRO_IMAGE_IMPORT_Z1AoUiI], ["./paintings/void (sealed).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fvoid-sealed.mdx", __ASTRO_IMAGE_IMPORT_Bsj26], ["./paintings/rebirth.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Frebirth-glint.mdx", __ASTRO_IMAGE_IMPORT_ZrAeNr]]);
		