
import __ASTRO_IMAGE_IMPORT_jkrTE from "../../images/drawings/cassandraopeia.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpage%2FHome.mdx";
import __ASTRO_IMAGE_IMPORT_ZXSVRg from "../../images/paintings/being here.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fbeing-here.mdx";
import __ASTRO_IMAGE_IMPORT_m1ldD from "../../images/paintings/birthing (seed).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fbirthing-seed.mdx";
import __ASTRO_IMAGE_IMPORT_25VxpA from "../../images/paintings/dying (glint).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fdying-glint.mdx";
import __ASTRO_IMAGE_IMPORT_23BbKt from "../../images/drawings/cassandraopeia.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fcassandraopeia.mdx";
import __ASTRO_IMAGE_IMPORT_TLXPN from "../../images/paintings/flower meditation (quartz).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fflower-meditation-quartz.mdx";
import __ASTRO_IMAGE_IMPORT_1o4g0b from "../../images/paintings/fluidly (in the water).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Ffluidly-in-the-water.mdx";
import __ASTRO_IMAGE_IMPORT_Z2eovND from "../../images/paintings/magic clover.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fmagic-clover.mdx";
import __ASTRO_IMAGE_IMPORT_Z1D4tt3 from "../../images/paintings/my wish for you (safe here).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fmy-wish-for-you.mdx";
import __ASTRO_IMAGE_IMPORT_Z1DfzXv from "../../images/paintings/rebirth.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Frebirth.mdx";
import __ASTRO_IMAGE_IMPORT_Z1BlheK from "../../images/paintings/reflecting (eclipse).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Freflecting-eclipse.mdx";
import __ASTRO_IMAGE_IMPORT_1ltvTJ from "../../images/drawings/sea.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fsea.mdx";
import __ASTRO_IMAGE_IMPORT_MfbQC from "../../images/paintings/submerged.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fsubmerged.mdx";
import __ASTRO_IMAGE_IMPORT_ZLOUOb from "../../images/drawings/suspended.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fsuspended.mdx";
import __ASTRO_IMAGE_IMPORT_N00jf from "../../images/drawings/suspended.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Ftemplate-art.mdx";
import __ASTRO_IMAGE_IMPORT_Z1tdngM from "../../images/paintings/void (sealed).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fvoid-sealed.mdx";
export default new Map([["../../images/drawings/cassandraopeia.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpage%2FHome.mdx", __ASTRO_IMAGE_IMPORT_jkrTE], ["../../images/paintings/being here.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fbeing-here.mdx", __ASTRO_IMAGE_IMPORT_ZXSVRg], ["../../images/paintings/birthing (seed).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fbirthing-seed.mdx", __ASTRO_IMAGE_IMPORT_m1ldD], ["../../images/paintings/dying (glint).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fdying-glint.mdx", __ASTRO_IMAGE_IMPORT_25VxpA], ["../../images/drawings/cassandraopeia.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fcassandraopeia.mdx", __ASTRO_IMAGE_IMPORT_23BbKt], ["../../images/paintings/flower meditation (quartz).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fflower-meditation-quartz.mdx", __ASTRO_IMAGE_IMPORT_TLXPN], ["../../images/paintings/fluidly (in the water).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Ffluidly-in-the-water.mdx", __ASTRO_IMAGE_IMPORT_1o4g0b], ["../../images/paintings/magic clover.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fmagic-clover.mdx", __ASTRO_IMAGE_IMPORT_Z2eovND], ["../../images/paintings/my wish for you (safe here).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fmy-wish-for-you.mdx", __ASTRO_IMAGE_IMPORT_Z1D4tt3], ["../../images/paintings/rebirth.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Frebirth.mdx", __ASTRO_IMAGE_IMPORT_Z1DfzXv], ["../../images/paintings/reflecting (eclipse).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Freflecting-eclipse.mdx", __ASTRO_IMAGE_IMPORT_Z1BlheK], ["../../images/drawings/sea.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fsea.mdx", __ASTRO_IMAGE_IMPORT_1ltvTJ], ["../../images/paintings/submerged.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fsubmerged.mdx", __ASTRO_IMAGE_IMPORT_MfbQC], ["../../images/drawings/suspended.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fsuspended.mdx", __ASTRO_IMAGE_IMPORT_ZLOUOb], ["../../images/drawings/suspended.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Ftemplate-art.mdx", __ASTRO_IMAGE_IMPORT_N00jf], ["../../images/paintings/void (sealed).JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fvoid-sealed.mdx", __ASTRO_IMAGE_IMPORT_Z1tdngM]]);
		