media:
    input: src/images
    output: /src/images
    # - name: paintings
    #   input: src/images/paintings
    # - name: drawings
    # - name: photos
    # - name: global
content:
    - name: pages
      label: Pages
      path: src/content/pages/
      type: collection
      fields: 
        - name: title
        - name: description
        - name: featured_image
        - name: selected_artworks
        - name: tag
        - name: collection
    - name: art
      label: Artwork
      type: collection
      path: src/content/art
# components:
 #   - slider:
  #    label: Slider
    #  type: block
