media:
    input: src/images
    output: /src/images
    # - name: paintings
    #   input: src/images/paintings
    # - name: drawings
    # - name: photos
    # - name: global
content: src/content
# components:
 #   - slider:
  #    label: Slider
    #  type: block
